- README.md
- web/README.md
> Sk 36/setup instruction readme

- .gitignore
- web/app/Enums/LogType.php
- web/app/Http/Controllers/AdminController.php
- web/app/Http/Controllers/Auth/LoginController.php
- web/app/Http/Controllers/AuthController.php
- web/app/Http/Controllers/BeneficiaryController.php
- web/app/Http/Controllers/CareManagerController.php
- web/app/Http/Controllers/CareWorkerController.php
- web/app/Http/Controllers/FamilyMemberController.php
- web/app/Http/Controllers/MessageController.php
- web/app/Http/Controllers/NotificationsController.php
- web/app/Http/Controllers/PasswordResetController.php
- web/app/Http/Controllers/WeeklyCareController.php
- web/app/Models/Log.php
- web/app/Services/LogService.php
- web/database/migrations/2025_05_07_161820_create_logs_table.php
- web/package.json
AdminController
AuthController
LoginController
BeneficiaryController
CareManagerController
CareWorkerController
FamilyMemberController.php
NotificationsController.php
WeeklyCareController.php
MessageController.php
PasswordResetController.php
> Logs modification

- web/app/Http/Controllers/Api/BeneficiaryApiController.php
> Beneficiary API Controller modification

- web/app/Http/Controllers/BeneficiaryController.php
> Undefined variable in BeneficiaryController

- web/app/Http/Controllers/Api/ReportsApiController.php
- web/routes/api.php
Added authenticated API endpoints for listing, viewing, and updating reports in ReportsApiController. Routes are protected with Sanctum middleware.
> Add API routes for reports management (list, view, update)

- web/app/Http/Controllers/Api/FamilyMemberApiController.php
- web/routes/api.php
Aligned FamilyMemberApiController and routes with web logic, enforced role checks, validation, and consistent responses.
> Refactor Family Member API for mobile parity

- web/app/Http/Controllers/Api/FamilyMemberApiController.php
- web/app/Http/Controllers/Api/WeeklyCarePlanApiController.php
- web/routes/api.php
Implemented WeeklyCarePlanApiController with strict validation and business logic to allow authenticated users to create Weekly Care Plans via the API, including vital signs and interventions. Route registered for POST /weekly-care-plans.
> Add API endpoint for creating Weekly Care Plans

- web/app/Exports/BudgetsExport.php
- web/app/Exports/ExpensesExport.php
- web/app/Http/Controllers/Api/InternalAppointmentsApiController.php
- web/app/Http/Controllers/Api/VisitationApiController.php
- web/app/Http/Controllers/ExpenseTrackerController.php
- web/app/Models/BudgetAllocation.php
- web/app/Models/BudgetType.php
- web/app/Models/Expense.php
- web/app/Models/ExpenseCategory.php
- web/database/factories/BudgetAllocationFactory.php
- web/database/factories/BudgetTypeFactory.php
- web/database/factories/ExpenseCategoryFactory.php
- web/database/factories/ExpenseFactory.php
- web/database/migrations/2025_05_22_151411_create_expense_categories_table.php
- web/database/migrations/2025_05_22_151455_create_budget_types_table.php
- web/database/migrations/2025_05_22_151512_create_expenses_table.php
- web/database/migrations/2025_05_22_151537_create_budget_allocations_table.php
- web/database/seeders/DatabaseSeeder.php
- web/resources/views/admin/adminExpenseTracker.blade.php
- web/routes/adminRoutes.php
- web/routes/api.php
Removed all write methods and added endpoints for calendar events, appointment types, staff, beneficiaries, and family members. Ensured all endpoints are read-only and support role-based filtering for mobile parity with the web controller.
> Refactor InternalAppointmentsApiController for read-only mobile use

- web/app/Http/Controllers/Api/UserApiController.php
- web/app/Http/Controllers/Api/ViewAccountProfileApiController.php
- web/routes/api.php
also removed route of old controller
NOTE: Pushed to wrong branch, here, instead of branch for ticket SK-84 Account Profile Refactor.
> Account profile picture display

- web/app/Http/Controllers/Api/AdminApiController.php
> Add line to use User model

- web/app/Services/UploadService.php
- web/config/filesystems.php
Working file upload and retrieval
> Sk 78/upload service

- web/app/Http/Controllers/Api/AuthApiController.php
- web/app/Http/Controllers/Api/BeneficiaryApiController.php
- web/app/Http/Controllers/Api/FamilyMemberApiController.php
- web/app/Observers/BeneficiaryObserver.php
- web/app/Observers/FamilyMemberObserver.php
- web/app/Providers/AppServiceProvider.php
- web/database/migrations/2025_04_30_174707_create_users_table.php
- Enhanced search and filter functionality in BeneficiaryApiController.
- Updated validation rules for required fields in store and update methods.
- Improved handling of file uploads, ensuring old files are deleted when new ones are uploaded.
- Introduced BeneficiaryObserver and FamilyMemberObserver to manage UnifiedUser creation and updates upon beneficiary and family member changes.
- Modified migration for users table to accommodate beneficiaries and family members, including unique username handling.
- Adjusted the logic for copying existing beneficiaries and family members into the users table during migration.
> Refactor Beneficiary and FamilyMember management

- web/app/Http/Controllers/Api/AdminApiController.php
- web/app/Http/Controllers/Api/AuthApiController.php
- web/app/Http/Controllers/Api/CareManagerApiController.php
- web/app/Http/Controllers/Api/CareWorkerApiController.php
- web/app/Http/Controllers/Api/ReportsApiController.php
- web/app/Http/Controllers/Api/WeeklyCarePlanApiController.php
- Added deletion of existing files before uploading new ones for administrators, care managers, and care workers.
- Implemented retrieval of user photos based on user type during login and user info retrieval.
- Updated the ReportsApiController to include a comment indicating it should be unused.
> sk-78: Enhance file upload handling and user photo retrieval

- web/app/Http/Controllers/Api/AdminApiController.php
- web/app/Http/Controllers/Api/AuthApiController.php
- web/app/Http/Controllers/Api/BeneficiaryApiController.php
- web/app/Http/Controllers/Api/CareManagerApiController.php
- web/app/Http/Controllers/Api/CareWorkerApiController.php
- web/app/Http/Controllers/Api/FamilyMemberApiController.php
- web/app/Http/Controllers/Api/ViewAccountProfileApiController.php
- web/app/Models/Appointment.php
- web/app/Models/Beneficiary.php
- web/app/Observers/BeneficiaryObserver.php
- web/app/Observers/FamilyMemberObserver.php
- web/routes/api.php
Refactor file uploads in CareManagerApiController and CareWorkerApiController to use associative array for filename; enhance FamilyMemberApiController to prevent deletion if family member is primary caregiver or has acknowledged care plans; improve ViewAccountProfileApiController to handle user roles and return detailed profile information; add appointmentType relationship in Appointment model; extend Beneficiary model with familyMembers and assignedCareWorker relationships; implement status management in BeneficiaryObserver and FamilyMemberObserver; add API route for changing family member status.
> sk-102/mobile-api-fix: fix 1

- web/app/Http/Controllers/Api/BeneficiaryApiController.php
- web/app/Http/Controllers/Api/FamilyMemberApiController.php
- web/routes/api.php
- Added export functionality for beneficiaries and family members as CSV.
- Updated routes to include export endpoints.
- Removed destroy and restore methods from FamilyMemberApiController.
- Improved validation and error handling in the export methods.
> Mobile API fix 2

- web/app/Http/Controllers/EmergencyAndRequestController.php
- web/app/Http/Controllers/FamilyPortalCarePlanController.php
- web/app/Http/Controllers/FamilyPortalEmergencyServiceRequestController.php
- web/app/Http/Controllers/VisitationController.php
- web/resources/views/admin/adminEmergencyRequest.blade.php
- web/resources/views/beneficiaryPortal/viewAllCarePlan.blade.php
- web/resources/views/beneficiaryPortal/visitationSchedule.blade.php
- web/resources/views/careManager/careManagerEmergencyRequest.blade.php
- web/resources/views/familyPortal/viewAllCarePlan.blade.php
- web/resources/views/familyPortal/visitationSchedule.blade.php
Notes should only be visible to COSE staff in responding to EN and SR, also notifications
Notify careworker on acknowledge
Seeder adjustment - family email addresses and invalid formatting name on signature
> Bug fixes test

- web/app/Http/Controllers/BeneficiaryController.php
- web/app/Models/Beneficiary.php
- web/database/migrations/2025_03_12_163209_create_beneficiaries_table.php
- web/resources/views/admin/addBeneficiary.blade.php
- web/resources/views/admin/editBeneficiary.blade.php
- web/resources/views/admin/testGoogleMap.blade.php
- web/resources/views/careManager/addBeneficiary.blade.php
- web/resources/views/careManager/editBeneficiary.blade.php
- web/resources/views/careWorker/addBeneficiary.blade.php
- web/resources/views/careWorker/editBeneficiary.blade.php
- web/routes/api.php
- Added Google Maps functionality to add and edit beneficiary forms.
- Included latitude and longitude fields to store map location.
- Updated Beneficiary model to include map_location attribute.
- Created a new testGoogleMap view for testing map features.
- Modified API routes to include commented test route for Google Maps.
> sk-114: Implement Google Maps integration for Beneficiary location

- web/app/Http/Controllers/Api/Portal/CarePlanApiController.php
- web/app/Http/Controllers/Api/Portal/EmergencyServiceRequestApiController.php
- web/app/Http/Controllers/Api/RecordsManagementApiController.php
- web/app/Http/Controllers/Api/ShiftApiController.php
- web/app/Http/Controllers/Api/ShiftTrackApiController.php
- web/app/Http/Controllers/Api/WeeklyCarePlanApiController.php
- web/app/Services/NotificationService.php
- Added notification service to notify care managers on various actions (e.g., care plan updates, service requests).
- Integrated notification calls in multiple controllers: CarePlanApiController, EmergencyServiceRequestApiController, ShiftApiController, ShiftTrackApiController, WeeklyCarePlanApiController.
- Enhanced NotificationService to include a method for notifying all care managers.
> notifications: Implement notification system for care managers

- web/app/Http/Controllers/Api/ShiftApiController.php
- web/app/Http/Controllers/Api/ShiftTrackApiController.php
- web/app/Models/Visitation.php
- Refactor visitation retrieval to use VisitationOccurrence model.
- Implement checks for recurring visitations in event logging.
- Adjust status handling for visitations based on occurrence dates.
> sk-88: Update visitation handling for occurrences and event logging

- web/public/css/message-dropdown.css
- web/public/css/portalNavbar.css
- web/resources/views/components/beneficiaryPortalNavbar.blade.php
> Notification badge

- web/app/Providers/AppServiceProvider.php
- web/database/factories/BudgetAllocationFactory.php
- web/database/factories/ExpenseFactory.php
- web/database/seeders/DatabaseSeeder.php
- Enabled HTTPS in AppServiceProvider
- Cached admin and budget type IDs in BudgetAllocationFactory
- Added detailed budget type descriptions in BudgetAllocationFactory
- Cached category IDs and added expense templates in ExpenseFactory
- Updated expense generation logic in DatabaseSeeder
> expense: Update factories and seeder for improved data generation

- web/app/Console/Commands/UpdateVisitationStatuses.php
- web/app/Http/Controllers/AdminController.php
- web/app/Http/Controllers/BeneficiaryController.php
- web/app/Http/Controllers/CareManagerController.php
- web/app/Http/Controllers/CareWorkerController.php
- web/app/Http/Controllers/EmergencyAndRequestController.php
- web/app/Http/Controllers/ExpenseTrackerController.php
- web/app/Http/Controllers/FamilyMemberController.php
- web/app/Http/Controllers/FamilyPortalEmergencyServiceRequestController.php
- web/app/Http/Controllers/MedicationScheduleController.php
- web/app/Http/Controllers/VisitationController.php
- web/app/Http/Controllers/WeeklyCareController.php
- web/app/Notifications/ExpoPushNotification.php
- web/app/Providers/AppServiceProvider.php
- web/app/Services/NotificationService.php
- web/bootstrap/providers.php
- web/composer.json
- web/composer.lock
- web/routes/api.php
- Introduced ExpoPushNotification class for handling Expo push notifications.
- Updated api.php to include commented-out test routes for token registration, sending push notifications, and checking token existence.
- Integrated NotificationService for managing notifications in the API routes.
> Add ExpoPushNotification class

- web/app/Console/Commands/SendAppointmentReminders.php
- web/app/Console/Commands/SendExactAppointmentReminders.php
- web/app/Console/Commands/SendExactTimeMedicationReminders.php
- web/app/Console/Commands/SendExactVisitationReminders.php
- web/app/Console/Commands/SendMedicationReminders.php
- web/app/Http/Controllers/InternalAppointmentsController.php
- Introduced NotificationService for sending notifications in SendAppointmentReminders, SendExactAppointmentReminders, SendExactTimeMedicationReminders, SendExactVisitationReminders, and SendMedicationReminders.
- Removed direct Notification model usage in favor of NotificationService methods.
- Updated InternalAppointmentsController to utilize NotificationService for notifying appointment participants.
> commands: Refactor notification handling in commands

- web/app/Http/Controllers/Api/AuthApiController.php
- web/app/Http/Controllers/Api/FcmApiController.php
- web/app/Models/Beneficiary.php
- web/app/Models/FamilyMember.php
- web/app/Models/FcmToken.php
- web/app/Models/MobileDevice.php
- web/app/Models/User.php
- web/app/Services/NotificationService.php
- web/database/migrations/2025_06_03_013346_create_mobile_devices_table.php
- web/database/migrations/2025_06_03_013347_create_fcm_tokens_table.php
- web/database/migrations/2025_06_28_230527_modify_fcm_tokens_table_structure.php
- web/routes/api.php
- web/routes/apiBeneficiaryRoutes.php
- web/routes/apiFamilyRoutes.php
Reverts TechBrigadeDev/sulong-kalinga#221
> Revert "push notifications api multi device"

- web/app/Http/Controllers/Api/Portal/EmergencyServiceRequestApiController.php
- web/app/Http/Controllers/EmergencyAndRequestController.php
- web/app/Http/Controllers/NotifyCareManagerController.php
- web/app/Services/NotificationService.php
- web/resources/views/emails/care-manager-notification.blade.php
- web/routes/api.php
- Added email notification functionality for care managers in NotificationService.
- Implemented NotifyCareManagerController for testing email notifications.
- Updated existing notification methods to include email notifications for service requests and emergency notices.
- Created a Blade view for care manager email notifications.
04f58f
> cm-email: Email notification for care managers

- web/app/Http/Controllers/EmergencyAndRequestController.php
- format of email notification content to include care worker name for follow ups
- removed triggers for care manager actions in emergency/service
> format and removal

- web/app/Http/Controllers/Api/BeneficiaryApiController.php
- web/app/Http/Controllers/Api/Portal/CarePlanApiController.php
- web/app/Http/Controllers/Api/RecordsManagementApiController.php
also change null to blank string for photo url if there is no photo in updateWeekly
update confirmed_by value in visitation if same date as wcp acknowledge
> revert change in beneficiary index method
